add_library(bench_up STATIC up_ref.c)
target_include_directories(bench_up PRIVATE ${B3})
target_link_libraries(bench_up PRIVATE b3stock)
add_executable(bench bench.c)
target_include_directories(bench PRIVATE ${OPENSSL_INCLUDE_DIR} ${CMAKE_SOURCE_DIR}/test)
target_link_libraries(bench PRIVATE bench_up b3stock ${OPENSSL_CRYPTO_LIBRARY})
if(NOT MSVC)
  target_compile_options(bench PRIVATE -O2 -Wno-deprecated-declarations)
  target_link_libraries(bench PRIVATE m)
endif()
