find_path(OPENSSL_INCLUDE_DIR openssl/core_dispatch.h
          HINTS ${OPENSSL_ROOT_DIR}/include $ENV{OPENSSL_ROOT_DIR}/include)
if(NOT OPENSSL_INCLUDE_DIR)
  message(FATAL_ERROR "OpenSSL headers not found: pass -DOPENSSL_INCLUDE_DIR=<dir containing openssl/core_dispatch.h>")
endif()
set(_ver "")
foreach(_f opensslv.h)
  if(EXISTS "${OPENSSL_INCLUDE_DIR}/openssl/${_f}")
    file(STRINGS "${OPENSSL_INCLUDE_DIR}/openssl/${_f}" _l REGEX "^# *define +OPENSSL_VERSION_(MAJOR|MINOR|PATCH) ")
    string(REGEX REPLACE "[^;]*OPENSSL_VERSION_MAJOR +([0-9]+)[^;]*;?" "\\1" _maj "${_l}")
  endif()
endforeach()
file(STRINGS "${OPENSSL_INCLUDE_DIR}/openssl/opensslv.h" _vl REGEX "OPENSSL_VERSION_(MAJOR|MINOR|PATCH) +[0-9]+")
set(OPENSSL_HEADERS_VERSION "")
foreach(_k MAJOR MINOR PATCH)
  foreach(_x ${_vl})
    if(_x MATCHES "OPENSSL_VERSION_${_k} +([0-9]+)")
      list(APPEND _parts ${CMAKE_MATCH_1})
    endif()
  endforeach()
endforeach()
string(REPLACE ";" "." OPENSSL_HEADERS_VERSION "${_parts}")
message(STATUS "OpenSSL headers: ${OPENSSL_INCLUDE_DIR} (version ${OPENSSL_HEADERS_VERSION})")
